### ISSUE TITLE
GPCC的安装

### ISSUE THREAD

**Issue by wanghy8166** [sanwishe/greenplum-exporter#2]
是否能提供一份gpcc的安装文档，满足greenplum-exporter正常运行的最小安装文档，再次感谢大佬！

**Comment by sanwishe** [comment]
不要意思，这是一个表示错误，不需要完整的gpcc，只需要gpperfmon就可以了。

```
${GPHOME}/bin/gpperfmon_install  --enable  --password 123456  --port 5432
```

这里的`--password 12345`就是数据库监控用户`gpmon`的密码。

**Comment by Zhushatianxia** [comment]
大佬，为什么我运行你编译的二进制吗，没有生效？是不是版本问题？我的greenplum是6.1.0 的。
还有个疑问是：
export GOROOT="/path/to/go"
export GOPROXY="{yourgoproxyaddress}"
这两个是什么含义

**Comment by sanwishe** [comment]
@wanghy8166 我已经把gpperfmon相关的操作添加到readme中了。有问题再issue，或者加我微信：sanwishe讨论。信息
