### ISSUE TITLE
二进制文件运行失败

### ISSUE THREAD

**Issue by Zhushatianxia** [sanwishe/greenplum-exporter#3]
大佬，我运行你编译的二进制文件时候，报错，无法打开报错如下：
cannot execute binary file？是不是版本问题？我的greenplum是6.1.0 的。
还有个疑问是：
export GOROOT="/path/to/go"
export GOPROXY="{yourgoproxyaddress}"
这两个是什么含义

**Comment by sanwishe** [comment]
我在release中方的是Linux amd64的版本，如果你是其他平台，需要自己编译哦。

对于你提到的：

```
export GOROOT="/path/to/go"
export GOPROXY="{yourgoproxyaddress}"
```

因为我是用Go Module方式进行依赖管理的，所以你需要设置你的GOROOT路径，此外由于GFW，Go Module无法从proxy.golang.org下载依赖，所以你要设置一个国内可访问的Go代理，比如‘https://goproxy.cn’。

**Comment by sanwishe** [comment]
抱歉，之前的文件确实有问题，重新release了一个新的版本，你再试试。
